--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    tags bigint[],
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

create table public.subscriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    contact_id bigint not null,
    total_sessions smallint not null default 20,
    purchased_at date not null default current_date,
    price numeric(10,2),
    notes text,
    sales_id bigint
);

alter table public.subscriptions
    add constraint subscriptions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

alter table public.subscriptions
    add constraint subscriptions_sales_id_fkey foreign key (sales_id) references public.sales(id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);

create index subscriptions_contact_id_idx on public.subscriptions using btree (contact_id);

create table public.sessions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    starts_at timestamp with time zone not null,
    duration_minutes smallint not null default 120,
    capacity smallint not null default 15,
    overbooking smallint not null default 2,
    notes text,
    sales_id bigint
);

alter table public.sessions
    add constraint sessions_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index sessions_starts_at_idx on public.sessions using btree (starts_at);

create table public.bookings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    session_id bigint not null,
    contact_id bigint not null,
    subscription_id bigint,
    type text not null default 'subscription' check (type in ('subscription', 'single', 'discovery')),
    status text not null default 'booked' check (status in ('booked', 'attended', 'cancelled', 'no_show')),
    cancelled_at timestamp with time zone,
    sales_id bigint
);

alter table public.bookings
    add constraint bookings_session_id_fkey foreign key (session_id) references public.sessions(id) on delete cascade;

alter table public.bookings
    add constraint bookings_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

alter table public.bookings
    add constraint bookings_subscription_id_fkey foreign key (subscription_id) references public.subscriptions(id) on delete set null;

alter table public.bookings
    add constraint bookings_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- Partial unique index: one active booking per (session, contact); re-booking after cancel is allowed
create unique index bookings_active_session_contact_idx
    on public.bookings (session_id, contact_id)
    where (status <> 'cancelled');

create index bookings_session_id_idx on public.bookings using btree (session_id);
create index bookings_contact_id_idx on public.bookings using btree (contact_id);
create index bookings_subscription_id_idx on public.bookings using btree (subscription_id);
