-- Migration: c90feeeb — Drawing-teacher remodel
-- Removes the B2B model (companies, deals, deal_notes + related views/triggers/functions)
-- and adds the drawing-school model (subscriptions, sessions, bookings + related objects).
--
-- Dependent objects dropped before their parents, then recreated:
--   DROP VIEW activity_log            (references companies, deals, deal_notes)
--   DROP VIEW contacts_summary        (references companies)
--   DROP VIEW companies_summary       (references companies, deals)
--   RECREATE activity_log             (contacts + contact_notes only)
--   RECREATE contacts_summary         (no company join; adds total_sessions_remaining)
-- All DROP … IF EXISTS; all CREATE … IF NOT EXISTS / OR REPLACE.

-- ============================================================
-- 1. DROP DEPENDENT VIEWS (referencing tables being deleted)
-- ============================================================

-- Drop views that reference companies / deals / deal_notes.
-- companies_summary, activity_log, contacts_summary all have
-- dependencies on those tables and must be dropped first.
-- We comment which dependents are affected per the skill rule.

-- Dependents of companies_summary: none (it's a leaf view).
-- Dependents of activity_log: none.
-- contacts_summary has no dependents in this schema.

DROP VIEW IF EXISTS public.companies_summary;
DROP VIEW IF EXISTS public.activity_log;
DROP VIEW IF EXISTS public.contacts_summary;

-- ============================================================
-- 2. DROP TRIGGERS ON TABLES BEING REMOVED
-- ============================================================

-- handle_company_saved trigger on companies
DROP TRIGGER IF EXISTS company_saved ON public.companies;
-- set_sales_id_default triggers on deals / deal_notes
DROP TRIGGER IF EXISTS set_deal_sales_id_trigger ON public.deals;
DROP TRIGGER IF EXISTS set_deal_notes_sales_id_trigger ON public.deal_notes;

-- ============================================================
-- 3. DROP RLS POLICIES ON TABLES BEING REMOVED
-- ============================================================

-- deal_notes policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.deal_notes;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.deal_notes;
DROP POLICY IF EXISTS "Deal Notes Update Policy" ON public.deal_notes;
DROP POLICY IF EXISTS "Deal Notes Delete Policy" ON public.deal_notes;

-- deals policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.deals;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.deals;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.deals;
DROP POLICY IF EXISTS "Deals Delete Policy" ON public.deals;

-- companies policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.companies;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.companies;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.companies;
DROP POLICY IF EXISTS "Company Delete Policy" ON public.companies;

-- ============================================================
-- 4. DROP B2B TABLES (cascades FKs automatically)
-- ============================================================

-- deal_notes references deals → drop first
DROP TABLE IF EXISTS public.deal_notes CASCADE;
-- deals references companies → drop next
DROP TABLE IF EXISTS public.deals CASCADE;
-- companies is now unreferenced
DROP TABLE IF EXISTS public.companies CASCADE;

-- ============================================================
-- 5. DROP contacts.company_id COLUMN
-- ============================================================

-- contacts had company_id FK to companies; cascade above removed the FK.
-- Now drop the column itself.
ALTER TABLE public.contacts DROP COLUMN IF EXISTS company_id;

-- ============================================================
-- 6. DROP handle_company_saved FUNCTION
-- ============================================================

DROP FUNCTION IF EXISTS public.handle_company_saved();

-- ============================================================
-- 7. ADD NEW TABLES
-- ============================================================

-- subscriptions
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    contact_id bigint not null,
    total_sessions smallint not null default 20,
    purchased_at date not null default current_date,
    price numeric(10,2),
    notes text,
    sales_id bigint
);

ALTER TABLE public.subscriptions
    ADD CONSTRAINT subscriptions_contact_id_fkey
    FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE
    NOT VALID;
ALTER TABLE public.subscriptions VALIDATE CONSTRAINT subscriptions_contact_id_fkey;

ALTER TABLE public.subscriptions
    ADD CONSTRAINT subscriptions_sales_id_fkey
    FOREIGN KEY (sales_id) REFERENCES public.sales(id)
    NOT VALID;
ALTER TABLE public.subscriptions VALIDATE CONSTRAINT subscriptions_sales_id_fkey;

CREATE INDEX IF NOT EXISTS subscriptions_contact_id_idx
    ON public.subscriptions USING btree (contact_id);

-- sessions
CREATE TABLE IF NOT EXISTS public.sessions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    starts_at timestamp with time zone not null,
    duration_minutes smallint not null default 120,
    capacity smallint not null default 15,
    overbooking smallint not null default 2,
    notes text,
    sales_id bigint
);

ALTER TABLE public.sessions
    ADD CONSTRAINT sessions_sales_id_fkey
    FOREIGN KEY (sales_id) REFERENCES public.sales(id)
    NOT VALID;
ALTER TABLE public.sessions VALIDATE CONSTRAINT sessions_sales_id_fkey;

CREATE INDEX IF NOT EXISTS sessions_starts_at_idx
    ON public.sessions USING btree (starts_at);

-- bookings
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    session_id bigint not null,
    contact_id bigint not null,
    subscription_id bigint,
    type text not null default 'subscription'
        check (type in ('subscription', 'single', 'discovery')),
    status text not null default 'booked'
        check (status in ('booked', 'attended', 'cancelled', 'no_show')),
    cancelled_at timestamp with time zone,
    sales_id bigint
);

ALTER TABLE public.bookings
    ADD CONSTRAINT bookings_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE
    NOT VALID;
ALTER TABLE public.bookings VALIDATE CONSTRAINT bookings_session_id_fkey;

ALTER TABLE public.bookings
    ADD CONSTRAINT bookings_contact_id_fkey
    FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE
    NOT VALID;
ALTER TABLE public.bookings VALIDATE CONSTRAINT bookings_contact_id_fkey;

ALTER TABLE public.bookings
    ADD CONSTRAINT bookings_subscription_id_fkey
    FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE SET NULL
    NOT VALID;
ALTER TABLE public.bookings VALIDATE CONSTRAINT bookings_subscription_id_fkey;

ALTER TABLE public.bookings
    ADD CONSTRAINT bookings_sales_id_fkey
    FOREIGN KEY (sales_id) REFERENCES public.sales(id)
    NOT VALID;
ALTER TABLE public.bookings VALIDATE CONSTRAINT bookings_sales_id_fkey;

-- Partial unique index: one active booking per (session, contact); re-booking after cancel is allowed
CREATE UNIQUE INDEX IF NOT EXISTS uq__bookings__session_contact__active
    ON public.bookings (session_id, contact_id)
    WHERE (status <> 'cancelled');

CREATE INDEX IF NOT EXISTS bookings_session_id_idx ON public.bookings USING btree (session_id);
CREATE INDEX IF NOT EXISTS bookings_contact_id_idx ON public.bookings USING btree (contact_id);
CREATE INDEX IF NOT EXISTS bookings_subscription_id_idx ON public.bookings USING btree (subscription_id);

-- ============================================================
-- 8. CHECK_SESSION_CAPACITY FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_session_capacity() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_capacity smallint;
  v_overbooking smallint;
  v_live_count bigint;
BEGIN
  -- Cancellations never consume capacity; skip check
  IF NEW.status = 'cancelled' THEN
    RETURN NEW;
  END IF;

  -- Read capacity and overbooking allowance for this session
  SELECT capacity, overbooking
    INTO v_capacity, v_overbooking
    FROM public.sessions
   WHERE id = NEW.session_id;

  -- Count existing live (non-cancelled) bookings for the session,
  -- excluding the current row on UPDATE so a status change doesn't
  -- count the row twice.
  SELECT COUNT(*)
    INTO v_live_count
    FROM public.bookings
   WHERE session_id = NEW.session_id
     AND status <> 'cancelled'
     AND (TG_OP = 'INSERT' OR id <> NEW.id);

  IF v_live_count >= (v_capacity + v_overbooking) THEN
    RAISE EXCEPTION
      'Session % is fully booked (capacity=%, overbooking=%, live_bookings=%)',
      NEW.session_id, v_capacity, v_overbooking, v_live_count
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

-- ============================================================
-- 9. UPDATE merge_contacts FUNCTION (remove company_id reference)
-- ============================================================

CREATE OR REPLACE FUNCTION "public"."merge_contacts"("loser_id" bigint, "winner_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
  merged_emails jsonb;
  merged_phones jsonb;
  merged_tags bigint[];
  winner_emails jsonb;
  loser_emails jsonb;
  winner_phones jsonb;
  loser_phones jsonb;
  email_map jsonb;
  phone_map jsonb;
BEGIN
  -- Fetch both contacts
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  -- 1. Reassign tasks from loser to winner
  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 2. Reassign contact notes from loser to winner
  UPDATE contact_notes SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 3. Merge contact data

  -- Get email arrays
  winner_emails := COALESCE(winner_contact.email_jsonb, '[]'::jsonb);
  loser_emails := COALESCE(loser_contact.email_jsonb, '[]'::jsonb);

  -- Merge emails with deduplication by email address
  -- Build a map of email -> email object, then convert back to array
  email_map := '{}'::jsonb;

  -- Add winner emails to map
  IF jsonb_array_length(winner_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_emails)-1 LOOP
      email_map := email_map || jsonb_build_object(
        winner_emails->i->>'email',
        winner_emails->i
      );
    END LOOP;
  END IF;

  -- Add loser emails to map (won't overwrite existing keys)
  IF jsonb_array_length(loser_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_emails)-1 LOOP
      IF NOT email_map ? (loser_emails->i->>'email') THEN
        email_map := email_map || jsonb_build_object(
          loser_emails->i->>'email',
          loser_emails->i
        );
      END IF;
    END LOOP;
  END IF;

  -- Convert map back to array
  merged_emails := (SELECT jsonb_agg(value) FROM jsonb_each(email_map));
  merged_emails := COALESCE(merged_emails, '[]'::jsonb);

  -- Get phone arrays
  winner_phones := COALESCE(winner_contact.phone_jsonb, '[]'::jsonb);
  loser_phones := COALESCE(loser_contact.phone_jsonb, '[]'::jsonb);

  -- Merge phones with deduplication by number
  phone_map := '{}'::jsonb;

  -- Add winner phones to map
  IF jsonb_array_length(winner_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_phones)-1 LOOP
      phone_map := phone_map || jsonb_build_object(
        winner_phones->i->>'number',
        winner_phones->i
      );
    END LOOP;
  END IF;

  -- Add loser phones to map (won't overwrite existing keys)
  IF jsonb_array_length(loser_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_phones)-1 LOOP
      IF NOT phone_map ? (loser_phones->i->>'number') THEN
        phone_map := phone_map || jsonb_build_object(
          loser_phones->i->>'number',
          loser_phones->i
        );
      END IF;
    END LOOP;
  END IF;

  -- Convert map back to array
  merged_phones := (SELECT jsonb_agg(value) FROM jsonb_each(phone_map));
  merged_phones := COALESCE(merged_phones, '[]'::jsonb);

  -- Merge tags (remove duplicates)
  merged_tags := ARRAY(
    SELECT DISTINCT unnest(
      COALESCE(winner_contact.tags, ARRAY[]::bigint[]) ||
      COALESCE(loser_contact.tags, ARRAY[]::bigint[])
    )
  );

  -- 4. Update winner with merged data
  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    gender = COALESCE(winner_contact.gender, loser_contact.gender),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    title = COALESCE(winner_contact.title, loser_contact.title),
    email_jsonb = merged_emails,
    phone_jsonb = merged_phones,
    linkedin_url = COALESCE(winner_contact.linkedin_url, loser_contact.linkedin_url),
    background = COALESCE(winner_contact.background, loser_contact.background),
    has_newsletter = COALESCE(winner_contact.has_newsletter, loser_contact.has_newsletter),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    sales_id = COALESCE(winner_contact.sales_id, loser_contact.sales_id),
    tags = merged_tags
  WHERE id = winner_id;

  -- 5. Delete loser contact
  DELETE FROM contacts WHERE id = loser_id;

  RETURN winner_id;
END;
$$;

-- ============================================================
-- 10. TRIGGERS FOR NEW TABLES
-- ============================================================

-- sales_id default triggers
CREATE OR REPLACE TRIGGER set_subscription_sales_id_trigger
    BEFORE INSERT ON public.subscriptions
    FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();

CREATE OR REPLACE TRIGGER set_session_sales_id_trigger
    BEFORE INSERT ON public.sessions
    FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();

CREATE OR REPLACE TRIGGER set_booking_sales_id_trigger
    BEFORE INSERT ON public.bookings
    FOR EACH ROW EXECUTE FUNCTION public.set_sales_id_default();

-- Capacity enforcement trigger on bookings
CREATE OR REPLACE TRIGGER check_session_capacity_trigger
    BEFORE INSERT OR UPDATE ON public.bookings
    FOR EACH ROW EXECUTE FUNCTION public.check_session_capacity();

-- ============================================================
-- 11. RLS FOR NEW TABLES
-- ============================================================

-- Subscriptions
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users"
    ON public.subscriptions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only"
    ON public.subscriptions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only"
    ON public.subscriptions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Subscription Delete Policy"
    ON public.subscriptions FOR DELETE TO authenticated USING (true);

-- Sessions
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users"
    ON public.sessions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only"
    ON public.sessions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only"
    ON public.sessions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Session Delete Policy"
    ON public.sessions FOR DELETE TO authenticated USING (true);

-- Bookings
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users"
    ON public.bookings FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only"
    ON public.bookings FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only"
    ON public.bookings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Booking Delete Policy"
    ON public.bookings FOR DELETE TO authenticated USING (true);

-- ============================================================
-- 12. GRANTS FOR NEW TABLES AND FUNCTION
-- ============================================================

GRANT ALL ON TABLE public.subscriptions TO anon;
GRANT ALL ON TABLE public.subscriptions TO authenticated;
GRANT ALL ON TABLE public.subscriptions TO service_role;

GRANT ALL ON TABLE public.sessions TO anon;
GRANT ALL ON TABLE public.sessions TO authenticated;
GRANT ALL ON TABLE public.sessions TO service_role;

GRANT ALL ON TABLE public.bookings TO anon;
GRANT ALL ON TABLE public.bookings TO authenticated;
GRANT ALL ON TABLE public.bookings TO service_role;

GRANT ALL ON SEQUENCE public.subscriptions_id_seq TO anon;
GRANT ALL ON SEQUENCE public.subscriptions_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.subscriptions_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.sessions_id_seq TO anon;
GRANT ALL ON SEQUENCE public.sessions_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.sessions_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.bookings_id_seq TO anon;
GRANT ALL ON SEQUENCE public.bookings_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.bookings_id_seq TO service_role;

GRANT EXECUTE ON FUNCTION public.check_session_capacity() TO anon;
GRANT EXECUTE ON FUNCTION public.check_session_capacity() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_session_capacity() TO service_role;

-- ============================================================
-- 13. RECREATE VIEWS
-- ============================================================

-- 13a. activity_log: drop B2B arms (company.created, deal.created, dealNote.created)
--      and the company_id column; keep contact.created + contactNote.created.
--      Column order vs old view: id, type, date, sales_id, contact, contact_note
--      (company/deal/deal_note columns removed — DROP+CREATE required for column removal).
CREATE OR REPLACE VIEW public.activity_log WITH (security_invoker = on) AS
SELECT
    ('contact.' || co.id || '.created') AS id,
    'contact.created' AS type,
    co.first_seen AS date,
    co.sales_id,
    to_json(co.*) AS contact,
    NULL::json AS contact_note
FROM public.contacts co
UNION ALL
SELECT
    ('contactNote.' || cn.id || '.created') AS id,
    'contactNote.created' AS type,
    cn.date,
    cn.sales_id,
    NULL::json AS contact,
    to_json(cn.*) AS contact_note
FROM public.contact_notes cn;

-- 13b. subscriptions_summary (new view)
CREATE OR REPLACE VIEW public.subscriptions_summary WITH (security_invoker = on) AS
SELECT
    s.id,
    s.created_at,
    s.contact_id,
    s.total_sessions,
    s.purchased_at,
    s.price,
    s.notes,
    s.sales_id,
    count(b.id) FILTER (WHERE b.status = 'attended') AS sessions_used,
    s.total_sessions - count(b.id) FILTER (WHERE b.status = 'attended') AS sessions_remaining
FROM public.subscriptions s
LEFT JOIN public.bookings b ON b.subscription_id = s.id
GROUP BY s.id;

-- 13c. contacts_summary: removed company_name/company join, added total_sessions_remaining.
--      Column positions 1..N match the old view (id through nb_tasks unchanged);
--      total_sessions_remaining is appended last.
CREATE OR REPLACE VIEW public.contacts_summary WITH (security_invoker = on) AS
SELECT
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text AS email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text AS phone_fts,
    count(DISTINCT t.id) FILTER (WHERE t.done_date IS NULL) AS nb_tasks,
    coalesce(sum(ss.sessions_remaining), 0) AS total_sessions_remaining
FROM public.contacts co
    LEFT JOIN public.tasks t ON co.id = t.contact_id
    LEFT JOIN public.subscriptions_summary ss ON co.id = ss.contact_id
GROUP BY co.id;

-- 13d. sessions_summary (new view)
CREATE OR REPLACE VIEW public.sessions_summary WITH (security_invoker = on) AS
SELECT
    s.id,
    s.created_at,
    s.starts_at,
    s.duration_minutes,
    s.capacity,
    s.overbooking,
    s.notes,
    s.sales_id,
    count(b.id) FILTER (WHERE b.status <> 'cancelled') AS nb_booked,
    count(b.id) FILTER (WHERE b.status = 'attended') AS nb_attended
FROM public.sessions s
LEFT JOIN public.bookings b ON b.session_id = s.id
GROUP BY s.id;

-- 13e. monthly_attendance (new view)
CREATE OR REPLACE VIEW public.monthly_attendance WITH (security_invoker = on) AS
SELECT
    (co.id::text || '-' || to_char(date_trunc('month', s.starts_at), 'YYYY-MM')) AS id,
    co.id AS contact_id,
    co.first_name,
    co.last_name,
    date_trunc('month', s.starts_at)::date AS month,
    count(b.id) AS sessions_attended
FROM public.bookings b
JOIN public.sessions s ON s.id = b.session_id
JOIN public.contacts co ON co.id = b.contact_id
WHERE b.status = 'attended'
GROUP BY co.id, co.first_name, co.last_name, date_trunc('month', s.starts_at);

-- ============================================================
-- 14. GRANTS FOR NEW VIEWS
-- ============================================================

GRANT ALL ON TABLE public.subscriptions_summary TO anon;
GRANT ALL ON TABLE public.subscriptions_summary TO authenticated;
GRANT ALL ON TABLE public.subscriptions_summary TO service_role;

GRANT ALL ON TABLE public.sessions_summary TO anon;
GRANT ALL ON TABLE public.sessions_summary TO authenticated;
GRANT ALL ON TABLE public.sessions_summary TO service_role;

GRANT ALL ON TABLE public.monthly_attendance TO anon;
GRANT ALL ON TABLE public.monthly_attendance TO authenticated;
GRANT ALL ON TABLE public.monthly_attendance TO service_role;

-- Re-grant contacts_summary and activity_log (re-created above; grants survive
-- CREATE OR REPLACE but not DROP+CREATE, so we re-issue them defensively).
GRANT ALL ON TABLE public.contacts_summary TO anon;
GRANT ALL ON TABLE public.contacts_summary TO authenticated;
GRANT ALL ON TABLE public.contacts_summary TO service_role;

GRANT ALL ON TABLE public.activity_log TO anon;
GRANT ALL ON TABLE public.activity_log TO authenticated;
GRANT ALL ON TABLE public.activity_log TO service_role;
