name: 🚀 Deploy
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    pages: write
    contents: write

jobs:
    deploy-demo:
        name: 🚀 Deploy (demo)
        runs-on: ubuntu-latest
        timeout-minutes: 10

        env:
            VITE_IS_DEMO: true
            VITE_INBOUND_EMAIL: ${{ vars.VITE_INBOUND_EMAIL }}
            VITE_ATTACHMENTS_BUCKET: ${{ vars.VITE_ATTACHMENTS_BUCKET || 'attachments' }}

        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: ⚙️ Setup git
              run: |
                  echo Deploying to pages to gh-pages
                  git config --global user.email support+actions@github.com
                  git config --global user.name github-actions-bot

            - name: 📥 Download deps
              run: npm ci

            - name: 🔨 Build
              run: npm run build:demo

            - name: 📡 Deploy GitHub pages
              run: npx gh-pages -d dist -b gh-pages
